<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.props" />

  <PropertyGroup>
    <AssemblyName>SweepZones</AssemblyName>
    <RootNamespace>SweepZones</RootNamespace>
    <Version>1.1.0</Version>
    <UsePLib>true</UsePLib>
    <ReferenceUnityUI>true</ReferenceUnityUI>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.targets" />

</Project>
