<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.props" />

  <PropertyGroup>
    <AssemblyName>SweepZones</AssemblyName>
    <RootNamespace>SweepZones</RootNamespace>
    <Version>1.4.1</Version>
    <UsePLib>true</UsePLib>
    <ReferenceUnityUI>true</ReferenceUnityUI>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\tool_icon.png" />
  </ItemGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\..\common\oni-mod.targets" />

</Project>
